/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATRICE_H_RPCGEN
#define _CALCULATRICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operation {
	long a;
	long b;
};
typedef struct operation operation;

#define CALC_PROG 0x69696969
#define CALC_VERSION_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ajouter 1
extern  long * ajouter_1(operation *, CLIENT *);
extern  long * ajouter_1_svc(operation *, struct svc_req *);
#define soustraire 2
extern  long * soustraire_1(operation *, CLIENT *);
extern  long * soustraire_1_svc(operation *, struct svc_req *);
#define multiplier 3
extern  long * multiplier_1(operation *, CLIENT *);
extern  long * multiplier_1_svc(operation *, struct svc_req *);
#define memoriser 4
extern  void * memoriser_1(int *, CLIENT *);
extern  void * memoriser_1_svc(int *, struct svc_req *);
#define extraire 5
extern  long * extraire_1(int *, CLIENT *);
extern  long * extraire_1_svc(int *, struct svc_req *);
#define allumer 6
extern  void * allumer_1(void *, CLIENT *);
extern  void * allumer_1_svc(void *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ajouter 1
extern  long * ajouter_1();
extern  long * ajouter_1_svc();
#define soustraire 2
extern  long * soustraire_1();
extern  long * soustraire_1_svc();
#define multiplier 3
extern  long * multiplier_1();
extern  long * multiplier_1_svc();
#define memoriser 4
extern  void * memoriser_1();
extern  void * memoriser_1_svc();
#define extraire 5
extern  long * extraire_1();
extern  long * extraire_1_svc();
#define allumer 6
extern  void * allumer_1();
extern  void * allumer_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation (XDR *, operation*);

#else /* K&R C */
extern bool_t xdr_operation ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATRICE_H_RPCGEN */
