/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "geometrie.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
surface_rectangle_1(rectangle *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SURFACE_RECTANGLE,
		(xdrproc_t) xdr_rectangle, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

rectangle *
creer_rectangle_1(coordonnees *argp, CLIENT *clnt)
{
	static rectangle clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CREER_RECTANGLE,
		(xdrproc_t) xdr_coordonnees, (caddr_t) argp,
		(xdrproc_t) xdr_rectangle, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

booleen *
inclus_1(param_inclus *argp, CLIENT *clnt)
{
	static booleen clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INCLUS,
		(xdrproc_t) xdr_param_inclus, (caddr_t) argp,
		(xdrproc_t) xdr_booleen, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
