/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "panoply.h"

bool_t
xdr_abonnement (XDR *xdrs, abonnement *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->credit))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client (XDR *xdrs, client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 64,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 64,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->password, 16,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mail, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_abonnement (xdrs, &objp->abo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vetement (XDR *xdrs, vetement *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->marque, 32,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
