/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PANOPLY_H_RPCGEN
#define _PANOPLY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct abonnement {
	int prix;
	int credit;
};
typedef struct abonnement abonnement;

struct client {
	char nom[64];
	char prenom[64];
	char password[16];
	char mail[256];
	abonnement abo;
};
typedef struct client client;

struct vetement {
	int prix;
	char marque[32];
};
typedef struct vetement vetement;

#define PANO_PROG 0x11223344
#define PANO_VERSION_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define nouveau_client 1
extern  client * nouveau_client_1(void *, CLIENT *);
extern  client * nouveau_client_1_svc(void *, struct svc_req *);
#define lister_abo 2
extern  void * lister_abo_1(void *, CLIENT *);
extern  void * lister_abo_1_svc(void *, struct svc_req *);
#define affecter_abo 3
extern  void * affecter_abo_1(client *, CLIENT *);
extern  void * affecter_abo_1_svc(client *, struct svc_req *);
#define modifier_abo 4
extern  void * modifier_abo_1(client *, CLIENT *);
extern  void * modifier_abo_1_svc(client *, struct svc_req *);
#define lister_marques 5
extern  void * lister_marques_1(void *, CLIENT *);
extern  void * lister_marques_1_svc(void *, struct svc_req *);
#define recherche_vetements_marque 6
extern  void * recherche_vetements_marque_1(void *, CLIENT *);
extern  void * recherche_vetements_marque_1_svc(void *, struct svc_req *);
#define louer_vetement 7
extern  void * louer_vetement_1(vetement *, CLIENT *);
extern  void * louer_vetement_1_svc(vetement *, struct svc_req *);
#define connexion 8
extern  int * connexion_1(void *, CLIENT *);
extern  int * connexion_1_svc(void *, struct svc_req *);
extern int pano_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define nouveau_client 1
extern  client * nouveau_client_1();
extern  client * nouveau_client_1_svc();
#define lister_abo 2
extern  void * lister_abo_1();
extern  void * lister_abo_1_svc();
#define affecter_abo 3
extern  void * affecter_abo_1();
extern  void * affecter_abo_1_svc();
#define modifier_abo 4
extern  void * modifier_abo_1();
extern  void * modifier_abo_1_svc();
#define lister_marques 5
extern  void * lister_marques_1();
extern  void * lister_marques_1_svc();
#define recherche_vetements_marque 6
extern  void * recherche_vetements_marque_1();
extern  void * recherche_vetements_marque_1_svc();
#define louer_vetement 7
extern  void * louer_vetement_1();
extern  void * louer_vetement_1_svc();
#define connexion 8
extern  int * connexion_1();
extern  int * connexion_1_svc();
extern int pano_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_abonnement (XDR *, abonnement*);
extern  bool_t xdr_client (XDR *, client*);
extern  bool_t xdr_vetement (XDR *, vetement*);

#else /* K&R C */
extern bool_t xdr_abonnement ();
extern bool_t xdr_client ();
extern bool_t xdr_vetement ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PANOPLY_H_RPCGEN */
